image: rust

stages:
  - pages
  - test
  - build

cache:
  paths:
    - target/release

before_script:
  - cargo build --release
  - export PATH=${PWD}/target/release:${PATH}

tests:
  stage: test
  image: rust
  script:
    - garden -vv test

checks:
  stage: test
  image: rust
  script:
    - rustup component add clippy
    - rustup component add rustfmt
    - garden -vv check/clippy
    - garden -vv check/fmt

build:amd64:
  stage: build
  image: rust
  script:
    - echo using pre-generated target/release/garden
    - cp -p target/release/garden garden
    - garden --version
  artifacts:
    paths:
      - garden

pages:
  stage: pages
  image: rust
  script:
    - apt-get update
    - apt-get install -y curl rsync
    - curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.44/mdbook-v0.4.44-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=target/release
    - garden doc -vv
    - mv target/doc doc/book/doc
    - mv doc/book public
    - echo "Read the generated documenation at $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  only:
    - dev
    - main
