[package]
name = "garden"
version = "1.1.0"
edition = "2018"

description = """
Garden Weaves Git Trees

Garden makes it easy to define, create, and run commands over collections
of configuration-defined multi-worktree Git environments.

"""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/davvid/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[features]
integration = []

[dependencies]
anyhow = "*"
argparse = "*"
atty = "*"
dirs = "*"
glob = "*"
shellexpand = "*"
shlex = "*"
subprocess = "*"
thiserror = "*"
xdg = "*"
yaml-rust = "*"
yansi = "*"
