[package]
name = "garden-tools"
version = "0.5.0-beta"
edition = "2021"
description = """
Cultivate Git Trees

Garden lets you define and run commands over collections of configuration-defined
multi-worktree Git environments."""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
license = "MIT"
readme = "README.md"
homepage = "https://davvid.github.io/garden/"
documentation = "https://docs.rs/garden-tools/latest/garden/"
repository = "https://github.com/davvid/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "4.0.32", features = ["derive"] }
clap_complete = "4.0.7"
crossbeam = "0.8"
dirs = "4.0"
glob = "0.3"
indextree = "4.3.1"
pathdiff = "0.2.1"
rayon = "1.5"
rm_rf = "0.6.2"
shellexpand = "2.1"
shlex = "1.1"
subprocess = "0.2"
thiserror = "1.0"
which = "4.3.0"
xdg = "2.4"
yaml-rust = { version = "0.5", package = "yaml-rust-davvid" }
yansi = "0.5"

[dev-dependencies]
assert_cmd = "2.0.2"
function_name = "0.2.0"

[lib]
name = "garden"

[[bin]]
name = "garden"
doc = false
test = false
