[package]
name = "garden"
version = "1.0.0"

description = """
Garden Weaves Git Trees

Garden makes it easy to define, create, and run commands over collections
of configuration-defined Git worktrees.  Gardens simplifies common development
tasks when working in a multi-worktree Git development environment.

"""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/davvid/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[features]
integration = []

[dependencies]
argparse = "*"
atty = "*"
glob = "*"
dirs = "*"
shellexpand = "*"
shlex = "*"
subprocess = "*"
xdg = "*"
yaml-rust = "*"
yansi = "*"
