[package]
name = "garden-tools"
version = "0.9.1"
edition = "2021"
description = """
Garden grows and cultivates collections of Git trees

Garden lets you define and run commands over collections of configuration-defined
multi-worktree Git environments."""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
license = "MIT"
readme = "README.md"
homepage = "https://garden-rs.gitlab.io"
documentation = "https://docs.rs/garden-tools/latest/garden"
repository = "https://gitlab.com/garden-rs/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
clap = { version = "4.1.1", features = ["derive", "string"] }
clap_complete = "4.1.0"
crossbeam = "0.8"
dirs = "4.0"
glob = "0.3"
indexmap = "1.9.2"
indextree = "4.3.1"
is-terminal = "0.4.9"
pathdiff = "0.2.1"
rayon = "1.5"
rm_rf = "0.6.2"
shellexpand = "2.1"
shell-words = "1.1"
shlex = "1.1"
strum = "0.25"
strum_macros = "0.25"
subprocess = "0.2"
thiserror = "1.0"
which = "4.3.0"
xdg = "2.4"
yaml-rust = { version = "0.5", package = "yaml-rust-davvid" }
yansi = "0.5"

[dev-dependencies]
assert_cmd = "2.0.2"
function_name = "0.2.0"

[lib]
name = "garden"

[[bin]]
name = "garden"
doc = false
test = false
