[package]
name = "garden"
version = "1.1.0"
edition = "2018"

description = """
Garden Weaves Git Trees

Garden makes it easy to define, create, and run commands over collections
of configuration-defined multi-worktree Git environments.

"""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/davvid/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[features]
integration = []

[dependencies]
anyhow = "1.0"
argparse = "0.2"
atty = "0.2"
dirs = "1.0"
glob = "0.2"
indextree = "4.3"
shellexpand = "1.0"
shlex = "0.1"
subprocess = "0.1"
thiserror = "1.0"
xdg = "2.2"
yaml-rust = { git = "git://github.com/davvid/yaml-rust.git", branch = "multiline-strings" }
yansi = "0.5"
