[package]
name = "garden-tools"
version = "0.3.0"
edition = "2021"

description = """
Garden Weaves Git Trees

Garden makes it easy to define, create, and run commands over collections
of configuration-defined multi-worktree Git environments.

"""
keywords = ["git", "development", "sandboxes", "vcs", "worktree"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/davvid/garden"
authors = ["David Aguilar <davvid@gmail.com>"]

[dependencies]
anyhow = "1.0"
argparse = "0.2"
atty = "0.2"
dirs = "4.0"
glob = "0.3"
indextree = "4.4"
pathdiff = "0.2.1"
shellexpand = "2.1"
shlex = "1.1"
subprocess = "0.2"
thiserror = "1.0"
xdg = "2.4"
yaml-rust = { version = "0.5", package = "yaml-rust-davvid" }
yansi = "0.5"

[dev-dependencies]
assert_cmd = "0.2"
function_name = "0.3"

[lib]
name = "garden"

[[bin]]
name = "garden"
doc = false
test = false
