[licenses]
allow = [
  # better_default
  "Apache-2.0",
  # egui
  "BSL-1.0",
  # egui
  "BSD-2-Clause",
  # encoding_rs
  "BSD-3-Clause",
  # egui
  "ISC",
  "MIT",
  # egui (fonts)
  "LicenseRef-UFL-1.0",
  # egui (fonts)
  "OFL-1.1",
  # dirs -> dirs-sys -> options-ext
  "MPL-2.0",
  # indexmap -> hashbrown
  "Unicode-3.0",
  # egui (fonts)
  "Ubuntu-font-1.0",
  # egui
  "Zlib",
]
