# This is the Gitlab CI pipeline for the pre-generated garden-rs.github.io repository
# and is installed to doc/book/.gitlab-ci.yml
stages:
  - pages

pages:
  image: alpine
  script:
    - apk --nocache add rsync
    - rsync -ar --exclude=public ./ ./public/
    - echo "Read the pre-generated documentation at $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  publish: public
  only:
    - main
