name: CI

on: [push, pull_request]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component rustfmt --component clippy --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --path .
      - name: Run clippy checks
        run: garden -vv check/clippy
      - name: Run format checks
        run: garden -vv check/fmt

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo install mdbook
      - run: cargo install --path .
      - name: Build documentation
        run: garden -vv doc

  test:
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
      - run: git config --global init.defaultBranch main
      - run: git config --global user.email garden-tools@crates.io
      - run: git config --global user.name Garden
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - name: Run build
        run: cargo build
      - name: Run tests
        run: cargo test -v
